---
title: '[Optional] Introduction to Computational Thinking & Simulation with R'
author: Christopher Gandrud
date: '2021-03-11'
slug: optional-r-basics-3
weight: 4
categories:
  - R
  - install
tags: [R, simulation, distributed, functions]
Categories: []
Description: ''
Tags: [R, simulation, distributed, functions]
bibliography: main.bib
---

> "What I cannot create, I do not understand" -- [Richard Feynman](https://archives.caltech.edu/pictures/1.10-29.jpg)

> "It is immoral to collect data before simulating the hypothesized data generating process." -- Andrew Gelman (what I remember of a comment to the Stanford Causal Inference Seminar in 2020)

## Motivation: Why simulate?

We've covered many of the basics of programming in R. Let's bring many of these concepts together to help us better understand our research problems, even before we gather any data: simulating **data generating processes**.

A data generating process is the process that creates the data in a data set. It can include, for example, both the social processes that result in migration data and even unexpected (or undesired) issues in the sampling procedure like non-random attrition.

Wait, why are we talking about simulating data generating processes in an introduction to R course? The

@gelmanhillaki2021
